name: daily-posts-now
region: nyc
services:
  - name: daily-posts-web
    source_dir: backend
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8000
    routes:
      - path: /
    build_command: >-
      python -m pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    run_command: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envs:
      - key: DJANGO_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "0"
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: CSRF_TRUSTED_ORIGINS
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SPACES_BUCKET
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: SPACES_REGION
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: SPACES_ENDPOINT
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: SPACES_CUSTOM_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
