# Generated by Django 5.2.8 on 2025-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
