# Generated by Django 5.2.8 on 2025-12-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=12),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
