# Generated by Django 5.2.8 on 2025-12-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_auditlog_options_alter_auditlog_action_and_more'),
        ('posts', '0006_comment_parent'),
    ]

    operations = [
    ]
