# Generated by Django 5.2.8 on 2025-12-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_group_is_public'),
        ('posts', '0007_merge_20251205_0428'),
    ]

    operations = [
    ]
