# Generated by Django 5.2.8 on 2025-12-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_group_cover'),
        ('posts', '0008_merge_0007_group_is_public_0007_merge_20251205_0428'),
    ]

    operations = [
    ]
