# Generated by Django 5.2.8 on 2025-12-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_auditlog_options_alter_auditlog_action_and_more'),
        ('posts', '0010_group_timeline'),
    ]

    operations = [
    ]
